name: GitHub Actions Workflow
run-name: ${{ github.actor }} is building Kai Chronicles
on: [push]
jobs:
  Build-Kai-Chronicles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: npm run downloaddata
      - run: npm run dist
      - name: List files in the output
        run: |
          ls ${{ github.workspace }}/dist
      - run: echo "🍏 This job's status is ${{ job.status }}."
